### PR TITLE
Feature - Search

### LINKED ISSUE #46: 🔎 Search by City
As the front implemented it, we need to be able to search a dose by City (more precise than by Department)

Useful links:
- https://github.com/CovidTrackerFr/vitemadose-front/blob/dev/src/views/vmd-rdv.view.ts
- https://github.com/CovidTrackerFr/vitemadose-front/blob/dev/src/state/State.ts

### PR DESCRIPTION
**Pull request by victor-sarda**
**⚠️ Warning: this PR contains some major changes, please review carefully**
---

## Description
 👋  Hello
This PR introduces a new search feature in the app. In the current app version, a user can only select a department in a static list. I added a search bar to allow search by city name, department name, department number or post code. The logic combines both local search (departments list) and API calls to the French [GeoAPI](https://geo.api.gouv.fr/).
When a user start typing in the search bar here's what happens:

- A `SearchStrategy` is defined according to the text. If the text is a 5 digits number, the search strategy will be set to `withPostCode` and an API call will be made to the right endpoint (there is no autocompletion for that one). If the text is a `String` (more than one character), it'll be set to `withName`, the city endpoint will be called and a list of found cities (limit is 15) will be show to the user (with autocompletion). A local search in our departments list is also performed. If the text is 1 character or less, the local departments list will be displayed again.
- When a user selects a result in the list, it'll be saved in `UserDefaults` to show the recent searches on the home (3 max). The result is passed to the vaccination centres list view model. It contains the location name, department code, near departments codes (found in a local list) and the coordinates if the selected result is a city.

The vaccination centres list loads the data for the search result department code **and** the near departments codes concurrently (if any) and map them, filter them (75km radius) and sort them by distance from the selected city. In a future pull request, the option to filter by distance or appointment time will be added.

I've also added some smaller changes: 
- Local departments list (saves us one API call on the home page)
- Local near departments list
- Some useful variables on the VaccinationCentre model (formatted phone, formatted title, etc ...)
- Made our cells ViewDatas conform to `Identifiable` for extra safety
- Updated texts
- Code cleaning

I've updated the `HomeViewModel` tests to reflect the changes and will add another PR with new tests once the feature is fulled done.

## Attachments
|Home|Home|
|-|-|
|IMG_1493|IMG_1494|

|Search|Search|
|-|-|
|IMG_1495|IMG_1496|

---

Closes #46

### CODE REVIEW

**Review by NathanFallet — APPROVED** [review]
Seems ok

**Comment by NathanFallet** [comment]
Can #49 be merged on this branch to get sorting in search directly?

**Comment by victor-sarda** [comment]
> Can #49 be merged on this branch to get sorting in search directly?

We don't need to, it'll only make this PR bigger that it is already 😄 
For dependent PRs we should always wait for the base branch to be merged in `develop`. I'll try to set a rule on github for this 👍

**Review by PlugNPush — DISMISSED** [review]

**Review by pauljeannot — APPROVED** [review]
Amazing job!

**Pull request merged**
