### PR TITLE
[#111] Dynamic fonts for A11Y improvements

### PR DESCRIPTION
**Pull request by pylapp**
Application UI can be improved so as to help disabled users to read easily the textual content of the app.
Thus dynamic fonts must be used so as to allow the system to rescale the app, thing not possible today.

- [x] Use system fonts everywhere
- [x] Test with very small font size (with "higher font size" a11y enabled in the device)
- [x] Test with very big font size (with "higher font size" a11y enabled in the device)
- [x] Test withs several font sizes, without a11y option enabled

### CODE REVIEW

**Comment by pylapp** [comment]
@victor-sarda Feel free to contact me for any details and review. These small changes will be helpful for disabled users :)

**Comment by pylapp** [comment]
This merge request for issue #111  is ready for review 👍

@rozierguillaume Any news to review and accept this pull request?

**Comment by pylapp** [comment]
@victor-sarda I will fix these conflicts this week and notify you here when this merge request will be ready again.

**Comment by pylapp** [comment]
@victor-sarda Now merge conflicts have been solved.
In a nutshell, this merge request allows disabled user to increase or reduce the font size so as to have bugger or smaller texts.
However, to do that we have to use Apple text styles for the fonts.
Thus previously bold text is not bold anymore, but it's mainly decorative.
This merger request increases a lot the accessibility of the app :)

You can find below in attachments some screen shots.

#111_A11Y_list_maxize
#111_A11Y_list_default
#111_A11Y_footer_maxsize
#111_A11Y_footer_default
#111_A11Y_dashboard_maxsize
#111_A11Y_dashboard_default
#111_A11Y_centers_top_maxize
#111_A11Y_centers_maxsize
#111_A11Y_centers_default

**Comment by pylapp** [comment]
@victor-sarda This merge request is ready for review 👍

**Comment by victor-sarda** [comment]
> @victor-sarda This merge request is ready for review 👍

Amazing thanks! I'll have a look in the evening then :)

**Comment by pylapp** [comment]
@victor-sarda Ok! The result is not perfect at all I agree, nevertheless it is sometimes tricky to build efficient UI with such big texts. But it is a nice improvement from my point of view :)

**Comment by victor-sarda** [comment]
> @victor-sarda Ok! The result is not perfect at all I agree, nevertheless it is sometimes tricky to build efficient UI with such big texts. But it is a nice improvement from my point of view :)

I'm sorry I can't approve that :(
I understand supporting dynamic font sizes is an important one but it can't be done in a way that would change the whole app UI I'm afraid. I'm also not sure doing this in `xib` files is the best approach to be honest.

We could still support dynamic sizes **whilst** keeping UI as it is right now. One way would be to set the point size programmatically like this for instance:

```swift
 let pointSize  = UIFontDescriptor.preferredFontDescriptor(withTextStyle: UIFont.TextStyle.largeTitle).pointSize
 let titleFont: UIFont = .rounded(ofSize: pointSize, weight: .bold)
 ```
Here  is what it would look like:
|Small|Large|
|-|-|
|Simulator Screen Shot - iPhone 11 - 2021-05-20 at 17 48 42|Simulator Screen Shot - iPhone 11 - 2021-05-20 at 17 49 15|

We could even have a specific file with an enum that contains fonts we need so we can easily use them across the app and keep some consistency.
Of course, I'm open to suggestions and happy to discuss/agree on the best solution to support dynamic font sizes in the app!

**Comment by victor-sarda** [comment]
> I agree. To be honest I was focused only on the XIB, and didn’t think about defining point sizes programmatically. It seems much cleaner. I will submit new evolutions next Monday, keep it for me 😄

No worries! Can't wait to see it 🙏

**Comment by pylapp** [comment]
@victor-sarda Merge request ready for review 👍

**Review by victor-sarda — DISMISSED** [review]
Amazing one, thank you!

**Comment by victor-sarda** [comment]
@pylapp there's just one small conflict to fix and then I can merge 😊

**Comment by pylapp** [comment]
@victor-sarda And it's done 😃 
You can merge this request !
I hope it will be useful for the users 👍

**Comment by pylapp** [comment]
@victor-sarda Any way to see this merge request be merged?
Do you need some help?

Cheers 😄

**Review by victor-sarda — APPROVED** [review]
Sorry didn't see you fixed the conflict, please don't hesitate to request review again so I get notified 👍

**Comment by pylapp** [comment]
Yeah! ❤️

**Pull request merged**
